Test
ronron88882/Basic-python pull request #7
Opened 2023-07-04 08:37 UTC by ronron88882

2023-07-04 11:23 UTC, Ryu-111 commented on euclid.py
🔴 修正お願いします。
6行目以降を削除していますが、削除しなくて大丈夫です

2023-07-04 11:25 UTC, RyuichiSaito requested changes
🔴 修正お願いします。
`prime.py`をpushし忘れています。

2023-07-11 08:20 UTC, ronron88882 commented
すみません、prime.pyとは何番目の問題に当てはまりますでしょうか？

2023-07-11 10:36 UTC, RyuichiSaito commented
問1のprime_number.pyです。
それ以外はOKです！

2023-07-11 12:45 UTC, RyuichiSaito commented
LGTM！

2023-07-11 12:45 UTC, RyuichiSaito approved these changes

2023-07-12 06:11 UTC, merged